### ISSUE TITLE
기본 구조 수정

### ISSUE THREAD

**Issue by yolol312** [dbehdgns1215/Happiness-Charging-Station-Monitoring#1]
ChargerStateEntity 클래스 테이블 명, 고유 식별자 추가 및 외래키 재설정 수정 필요

**Comment by lulluralra** [comment]
Charger하고 ChargerState하고 1:1 매핑이라 굳이 추가 안했는데 고유 식별자 추가 필요할까요??

**Comment by yolol312** [comment]
제 컴퓨터에서는 고유 식별자가 없으니 오류가 발생하더라구요... 혹시 오류 발생 안 하시나요??

**Comment by lulluralra** [comment]
mysql 꼬여서 이번주 내로 확인할게요ㅜㅜ

**Comment by lulluralra** [comment]
ChargerStateEntity 고유키(id) 컬럼 추가 및 이에 따른 코드 수정 완료
